version: '3'
services:
    backend:
      image: imsv2-be-stg:latest
      tty: true
      restart: unless-stopped
      networks:
        - backend_network

networks:
  backend_network:
    name: gateway_network
    external: true
          