export enum STATUS_CODE {
  CREATED_SUCCESSFULLY = 201,
  UPDATED_SUCCESSFULLY = 202
}

export enum REQUEST_METHOD {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
}