version: '3'

services:
  app:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "8080:80"
    networks:
      - loadbalancer_network
    restart: unless-stopped
    volumes:
      - ./nginx.gateway.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx-c/gateway:/var/log/nginx

networks:
  loadbalancer_network:
    name: gateway_network
    external: true
    