version: '3'

services:
  frontend:
    image: imsv2-fe-dev:latest
    networks:
      - frontend_network
    restart: unless-stopped
    extra_hosts:
      - "dev-api-imsv2.nccsoft.vn:172.16.110.30"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx-c/fe-dev:/var/log/nginx

networks:
  frontend_network:
    name: gateway_network
    external: true
    